export const UPDATE_DONATIONS = 'UPDATE_DONATIONS';
export const UPDATE_BENEFACTORS = 'UPDATE_BENEFACTORS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_MULTIPLE_TO_CART = 'ADD_MULTIPLE_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const TOGGLE_CART = 'TOGGLE_CART';